Adminsite:
    type: entity
    table: adminsite
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        motdepasse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
