Categorie:
    type: entity
    table: categorie
    id:
        idcategorie:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
