Client:
    type: entity
    table: client
    id:
        idclient:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        motdepass:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
