Commentaire:
    type: entity
    table: commentaire
    indexes:
        fk_commentaire_produit1_idx:
            columns:
                - produit_idproduit
        fk_commentaire_client1_idx:
            columns:
                - client_idclient
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texteCommentaire:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: texte_commentaire
        date:
            type: date
            nullable: true
            comment: ''
    manyToOne:
        clientclient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_idclient:
                    referencedColumnName: idclient
            orphanRemoval: false
        produitproduit:
            targetEntity: Produit
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                produit_idproduit:
                    referencedColumnName: idproduit
            orphanRemoval: false
    lifecycleCallbacks: {  }
