Panier:
    type: entity
    table: panier
    indexes:
        fk_panier_client1_idx:
            columns:
                - client_idclient
    id:
        idpanier:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        montant:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
    manyToOne:
        clientclient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_idclient:
                    referencedColumnName: idclient
            orphanRemoval: false
    lifecycleCallbacks: {  }
