Produit:
    type: entity
    table: produit
    indexes:
        fk_produit_categorie1_idx:
            columns:
                - categorie_idcategorie
    id:
        idproduit:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        libelle:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        image:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        updated:
            type: datetime
            nullable:  true
        prix:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        quantitee:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks:
            prePersist:   [ lifecycleFileUpload ]
            preUpdate:    [ lifecycleFileUpload ]
        
      
      
      
    manyToOne:
        categoriecategorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categorie_idcategorie:
                    referencedColumnName: idcategorie
            orphanRemoval: false
    lifecycleCallbacks: {  }
