Reclamation:
    type: entity
    table: reclamation
    indexes:
        fk_reclamation_client1_idx:
            columns:
                - client_idclient
        fk_reclamation_magasin1_idx:
            columns:
                - magasin_idmagasin
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texte:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        date:
            type: date
            nullable: true
            comment: ''
    manyToOne:
        clientclient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_idclient:
                    referencedColumnName: idclient
            orphanRemoval: false
        magasinmagasin:
            targetEntity: Magasin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                magasin_idmagasin:
                    referencedColumnName: idmagasin
            orphanRemoval: false
    lifecycleCallbacks: {  }
