ResponsabeMagasin:
    type: entity
    table: responsabe_magasin
    indexes:
        fk_responsabe_magasin_magasin_idx:
            columns:
                - magasin_idmagasin
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        motdepasse:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        magasinmagasin:
            targetEntity: Magasin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                magasin_idmagasin:
                    referencedColumnName: idmagasin
            orphanRemoval: false
    lifecycleCallbacks: {  }
